//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 11:18:01 AM MEZ 
//


package scim.schema.v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the scim.schema.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EmployeeNumber_QNAME = new QName("urn:scim:schemas:extension:enterprise:1.0", "employeeNumber");
    private final static QName _Division_QNAME = new QName("urn:scim:schemas:extension:enterprise:1.0", "division");
    private final static QName _Organization_QNAME = new QName("urn:scim:schemas:extension:enterprise:1.0", "organization");
    private final static QName _CostCenter_QNAME = new QName("urn:scim:schemas:extension:enterprise:1.0", "costCenter");
    private final static QName _Bulk_QNAME = new QName("urn:scim:schemas:core:1.0", "Bulk");
    private final static QName _Response_QNAME = new QName("urn:scim:schemas:core:1.0", "Response");
    private final static QName _Group_QNAME = new QName("urn:scim:schemas:core:1.0", "Group");
    private final static QName _Error_QNAME = new QName("urn:scim:schemas:core:1.0", "Error");
    private final static QName _Operation_QNAME = new QName("urn:scim:schemas:core:1.0", "Operation");
    private final static QName _Resource_QNAME = new QName("urn:scim:schemas:core:1.0", "Resource");
    private final static QName _Manager_QNAME = new QName("urn:scim:schemas:extension:enterprise:1.0", "manager");
    private final static QName _User_QNAME = new QName("urn:scim:schemas:core:1.0", "User");
    private final static QName _Department_QNAME = new QName("urn:scim:schemas:extension:enterprise:1.0", "department");
    private final static QName _ServiceProviderConfig_QNAME = new QName("urn:scim:schemas:core:1.0", "ServiceProviderConfig");
    private final static QName _Schema_QNAME = new QName("urn:scim:schemas:core:1.0", "Schema");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: scim.schema.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.ChangePassword }
     * 
     */
    public ServiceProviderConfig.ChangePassword createServiceProviderConfigChangePassword() {
        return new ServiceProviderConfig.ChangePassword();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link User.Photos }
     * 
     */
    public User.Photos createUserPhotos() {
        return new User.Photos();
    }

    /**
     * Create an instance of {@link SchemaAttribute }
     * 
     */
    public SchemaAttribute createSchemaAttribute() {
        return new SchemaAttribute();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.Etag }
     * 
     */
    public ServiceProviderConfig.Etag createServiceProviderConfigEtag() {
        return new ServiceProviderConfig.Etag();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.Bulk }
     * 
     */
    public ServiceProviderConfig.Bulk createServiceProviderConfigBulk() {
        return new ServiceProviderConfig.Bulk();
    }

    /**
     * Create an instance of {@link Manager }
     * 
     */
    public Manager createManager() {
        return new Manager();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link SchemaAttribute.SubAttributes }
     * 
     */
    public SchemaAttribute.SubAttributes createSchemaAttributeSubAttributes() {
        return new SchemaAttribute.SubAttributes();
    }

    /**
     * Create an instance of {@link AuthenticationScheme }
     * 
     */
    public AuthenticationScheme createAuthenticationScheme() {
        return new AuthenticationScheme();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.AuthenticationSchemes }
     * 
     */
    public ServiceProviderConfig.AuthenticationSchemes createServiceProviderConfigAuthenticationSchemes() {
        return new ServiceProviderConfig.AuthenticationSchemes();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link User.Ims }
     * 
     */
    public User.Ims createUserIms() {
        return new User.Ims();
    }

    /**
     * Create an instance of {@link Schema }
     * 
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link User.PhoneNumbers }
     * 
     */
    public User.PhoneNumbers createUserPhoneNumbers() {
        return new User.PhoneNumbers();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Group.Members }
     * 
     */
    public Group.Members createGroupMembers() {
        return new Group.Members();
    }

    /**
     * Create an instance of {@link User.Entitlements }
     * 
     */
    public User.Entitlements createUserEntitlements() {
        return new User.Entitlements();
    }

    /**
     * Create an instance of {@link User.X509Certificates }
     * 
     */
    public User.X509Certificates createUserX509Certificates() {
        return new User.X509Certificates();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.Sort }
     * 
     */
    public ServiceProviderConfig.Sort createServiceProviderConfigSort() {
        return new ServiceProviderConfig.Sort();
    }

    /**
     * Create an instance of {@link User.Groups }
     * 
     */
    public User.Groups createUserGroups() {
        return new User.Groups();
    }

    /**
     * Create an instance of {@link User.Roles }
     * 
     */
    public User.Roles createUserRoles() {
        return new User.Roles();
    }

    /**
     * Create an instance of {@link Response.Errors }
     * 
     */
    public Response.Errors createResponseErrors() {
        return new Response.Errors();
    }

    /**
     * Create an instance of {@link User.Emails }
     * 
     */
    public User.Emails createUserEmails() {
        return new User.Emails();
    }

    /**
     * Create an instance of {@link CoreResource }
     * 
     */
    public CoreResource createCoreResource() {
        return new CoreResource();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.XmlDataFormat }
     * 
     */
    public ServiceProviderConfig.XmlDataFormat createServiceProviderConfigXmlDataFormat() {
        return new ServiceProviderConfig.XmlDataFormat();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link scim.schema.v2.Bulk.Operations }
     * 
     */
    public scim.schema.v2.Bulk.Operations createBulkOperations() {
        return new scim.schema.v2.Bulk.Operations();
    }

    /**
     * Create an instance of {@link User.Addresses }
     * 
     */
    public User.Addresses createUserAddresses() {
        return new User.Addresses();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.Patch }
     * 
     */
    public ServiceProviderConfig.Patch createServiceProviderConfigPatch() {
        return new ServiceProviderConfig.Patch();
    }

    /**
     * Create an instance of {@link Meta.Attributes }
     * 
     */
    public Meta.Attributes createMetaAttributes() {
        return new Meta.Attributes();
    }

    /**
     * Create an instance of {@link scim.schema.v2.Bulk }
     * 
     */
    public scim.schema.v2.Bulk createBulk() {
        return new scim.schema.v2.Bulk();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig.Filter }
     * 
     */
    public ServiceProviderConfig.Filter createServiceProviderConfigFilter() {
        return new ServiceProviderConfig.Filter();
    }

    /**
     * Create an instance of {@link SchemaSubAttribute }
     * 
     */
    public SchemaSubAttribute createSchemaSubAttribute() {
        return new SchemaSubAttribute();
    }

    /**
     * Create an instance of {@link MultiValuedAttribute }
     * 
     */
    public MultiValuedAttribute createMultiValuedAttribute() {
        return new MultiValuedAttribute();
    }

    /**
     * Create an instance of {@link Response.Resources }
     * 
     */
    public Response.Resources createResponseResources() {
        return new Response.Resources();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Schema.Attributes }
     * 
     */
    public Schema.Attributes createSchemaAttributes() {
        return new Schema.Attributes();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link ServiceProviderConfig }
     * 
     */
    public ServiceProviderConfig createServiceProviderConfig() {
        return new ServiceProviderConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:extension:enterprise:1.0", name = "employeeNumber")
    public JAXBElement<String> createEmployeeNumber(String value) {
        return new JAXBElement<String>(_EmployeeNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:extension:enterprise:1.0", name = "division")
    public JAXBElement<String> createDivision(String value) {
        return new JAXBElement<String>(_Division_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:extension:enterprise:1.0", name = "organization")
    public JAXBElement<String> createOrganization(String value) {
        return new JAXBElement<String>(_Organization_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:extension:enterprise:1.0", name = "costCenter")
    public JAXBElement<String> createCostCenter(String value) {
        return new JAXBElement<String>(_CostCenter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link scim.schema.v2.Bulk }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "Bulk")
    public JAXBElement<scim.schema.v2.Bulk> createBulk(scim.schema.v2.Bulk value) {
        return new JAXBElement<scim.schema.v2.Bulk>(_Bulk_QNAME, scim.schema.v2.Bulk.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "Response")
    public JAXBElement<Response> createResponse(Response value) {
        return new JAXBElement<Response>(_Response_QNAME, Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "Group")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Error }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "Error")
    public JAXBElement<Error> createError(Error value) {
        return new JAXBElement<Error>(_Error_QNAME, Error.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Operation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "Operation")
    public JAXBElement<Operation> createOperation(Operation value) {
        return new JAXBElement<Operation>(_Operation_QNAME, Operation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "Resource")
    public JAXBElement<Resource> createResource(Resource value) {
        return new JAXBElement<Resource>(_Resource_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Manager }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:extension:enterprise:1.0", name = "manager")
    public JAXBElement<Manager> createManager(Manager value) {
        return new JAXBElement<Manager>(_Manager_QNAME, Manager.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "User")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:extension:enterprise:1.0", name = "department")
    public JAXBElement<String> createDepartment(String value) {
        return new JAXBElement<String>(_Department_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceProviderConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "ServiceProviderConfig")
    public JAXBElement<ServiceProviderConfig> createServiceProviderConfig(ServiceProviderConfig value) {
        return new JAXBElement<ServiceProviderConfig>(_ServiceProviderConfig_QNAME, ServiceProviderConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Schema }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:scim:schemas:core:1.0", name = "Schema")
    public JAXBElement<Schema> createSchema(Schema value) {
        return new JAXBElement<Schema>(_Schema_QNAME, Schema.class, null, value);
    }

}
