//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.14 at 11:18:01 AM MEZ 
//


package scim.schema.v2;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for User complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 */
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
public class User extends CoreResource {

    private final String userName;
    private final Name name;
    private final String displayName;
    private final String nickName;
    private final String profileUrl;
    private final String title;
    private final String userType;
    private final String preferredLanguage;
    private final String locale;
    private final String timezone;
    private final Boolean active;
    private final String password;
    private final User.Emails emails;
    private final User.PhoneNumbers phoneNumbers;
    private final User.Ims ims;
    private final User.Photos photos;
    private final User.Addresses addresses;
    private final User.Groups groups;
    private final User.Entitlements entitlements;
    private final User.Roles roles;
    private final User.X509Certificates x509Certificates;
    private List<Object> any;

    private User(Builder builder) {
        this.userName = builder.userName;
        this.name = builder.name;
        this.displayName = builder.displayName;
        this.nickName = builder.nickName;
        this.profileUrl = builder.profileUrl;
        this.title = builder.title;
        this.userType = builder.userType;
        this.preferredLanguage = builder.preferredLanguage;
        this.locale = builder.locale;
        this.timezone = builder.timezone;
        this.active = builder.active;
        this.password = builder.password;
        //Not final because those are list, which are used to get enriched afterwards for easier usage.
        this.emails = builder.emails;
        this.phoneNumbers = builder.phoneNumbers;
        this.ims = builder.ims;
        this.photos = builder.photos;
        this.addresses = builder.addresses;
        this.groups = builder.groups;
        this.entitlements = builder.entitlements;
        this.roles = builder.roles;
        this.x509Certificates = builder.x509Certificates;
        this.any = builder.any;

    }

    public static class Builder {
        private final String userName;


        private Name name;
        private String displayName;
        private String nickName;
        private String profileUrl;
        private String title;
        private String userType;
        private String preferredLanguage;
        private String locale;
        private String timezone;
        private Boolean active;
        private String password;

        private User.Emails emails = new Emails();
        private User.PhoneNumbers phoneNumbers = new PhoneNumbers();
        private User.Ims ims = new Ims();
        private User.Photos photos = new Photos();
        private User.Addresses addresses = new Addresses();
        private User.Groups groups = new Groups();
        private User.Entitlements entitlements = new Entitlements();
        private User.Roles roles = new Roles();
        private User.X509Certificates x509Certificates = new X509Certificates();


        private List<Object> any;


        public Builder(String userName) {
            if (userName == null)
                throw new IllegalArgumentException("userName must not be null.");
            this.userName = userName;
        }

        public Builder setName(Name name) {
            this.name = name;
            return this;
        }

        public Builder setDisplayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        public Builder setNickName(String nickName) {
            this.nickName = nickName;
            return this;
        }

        public Builder setProfileUrl(String profileUrl) {
            this.profileUrl = profileUrl;
            return this;
        }

        public Builder setTitle(String title) {
            this.title = title;
            return this;
        }

        public Builder setUserType(String userType) {
            this.userType = userType;
            return this;
        }

        public Builder setPreferredLanguage(String preferredLanguage) {
            this.preferredLanguage = preferredLanguage;
            return this;
        }

        public Builder setLocale(String locale) {
            this.locale = locale;
            return this;
        }

        public Builder setTimezone(String timezone) {
            this.timezone = timezone;
            return this;
        }

        public Builder setActive(Boolean active) {
            this.active = active;
            return this;
        }

        public Builder setPassword(String password) {
            this.password = password;
            return this;
        }

        public Builder setEmails(Emails emails) {
            this.emails = emails;
            return this;
        }

        public Builder setPhoneNumbers(PhoneNumbers phoneNumbers) {
            this.phoneNumbers = phoneNumbers;
            return this;
        }

        public Builder setIms(Ims ims) {
            this.ims = ims;
            return this;
        }

        public Builder setPhotos(Photos photos) {
            this.photos = photos;
            return this;
        }

        public Builder setAddresses(Addresses addresses) {
            this.addresses = addresses;
            return this;
        }

        public Builder setGroups(Groups groups) {
            this.groups = groups;
            return this;
        }

        public Builder setEntitlements(Entitlements entitlements) {
            this.entitlements = entitlements;
            return this;
        }

        public Builder setRoles(Roles roles) {
            this.roles = roles;
            return this;
        }

        public Builder setX509Certificates(X509Certificates x509Certificates) {
            this.x509Certificates = x509Certificates;
            return this;
        }

        public Builder setAny(List<Object> any) {
            this.any = any;
            return this;
        }

        public User build() {
            return new User(this);
        }


    }


    /**
     * Gets the value of the userName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link Name }
     */
    public Name getName() {
        return name;
    }

    /**
     * Gets the value of the displayName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Gets the value of the nickName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * Gets the value of the profileUrl property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getProfileUrl() {
        return profileUrl;
    }

    /**
     * Gets the value of the title property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Gets the value of the userType property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getUserType() {
        return userType;
    }

    /**
     * Gets the value of the preferredLanguage property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPreferredLanguage() {
        return preferredLanguage;
    }

    /**
     * Gets the value of the locale property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Gets the value of the timezone property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTimezone() {
        return timezone;
    }

    /**
     * Gets the value of the active property.
     *
     * @return possible object is
     *         {@link Boolean }
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Gets the value of the password property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPassword() {
        return password;
    }

    /**
     * Gets the value of the emails property.
     *
     * @return possible object is
     *         {@link User.Emails }
     */
    public User.Emails getEmails() {
        return emails;
    }

    /**
     * Gets the value of the phoneNumbers property.
     *
     * @return possible object is
     *         {@link User.PhoneNumbers }
     */
    public User.PhoneNumbers getPhoneNumbers() {
        return phoneNumbers;
    }

    /**
     * Gets the value of the ims property.
     *
     * @return possible object is
     *         {@link User.Ims }
     */
    public User.Ims getIms() {
        return ims;
    }

    /**
     * Gets the value of the photos property.
     *
     * @return possible object is
     *         {@link User.Photos }
     */
    public User.Photos getPhotos() {
        return photos;
    }

    /**
     * Gets the value of the addresses property.
     *
     * @return possible object is
     *         {@link User.Addresses }
     */
    public User.Addresses getAddresses() {
        return addresses;
    }

    /**
     * Gets the value of the groups property.
     *
     * @return possible object is
     *         {@link User.Groups }
     */
    public User.Groups getGroups() {
        return groups;
    }

    /**
     * Gets the value of the entitlements property.
     *
     * @return possible object is
     *         {@link User.Entitlements }
     */
    public User.Entitlements getEntitlements() {
        return entitlements;
    }

    /**
     * Gets the value of the roles property.
     *
     * @return possible object is
     *         {@link User.Roles }
     */
    public User.Roles getRoles() {
        return roles;
    }

    /**
     * Gets the value of the x509Certificates property.
     *
     * @return possible object is
     *         {@link User.X509Certificates }
     */
    public User.X509Certificates getX509Certificates() {
        return x509Certificates;
    }

    /**
     * Gets the value of the any property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<>();
        }
        return this.any;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address" type="{urn:scim:schemas:core:1.0}address" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Addresses {

        private List<Address> address;

        /**
         * Gets the value of the address property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the address property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddress().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Address }
         */
        public List<Address> getAddress() {
            if (address == null) {
                address = new ArrayList<Address>();
            }
            return this.address;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="email" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Emails {

        private List<MultiValuedAttribute> email;

        /**
         * Gets the value of the email property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the email property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmail().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getEmail() {
            if (email == null) {
                email = new ArrayList<>();
            }
            return this.email;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entitlement" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Entitlements {

        private List<MultiValuedAttribute> entitlement;

        /**
         * Gets the value of the entitlement property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the entitlement property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntitlement().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getEntitlement() {
            if (entitlement == null) {
                entitlement = new ArrayList<>();
            }
            return this.entitlement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="group" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Groups {

        private List<MultiValuedAttribute> group;

        /**
         * Gets the value of the group property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the group property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroup().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getGroup() {
            if (group == null) {
                group = new ArrayList<MultiValuedAttribute>();
            }
            return this.group;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="im" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Ims {

        private List<MultiValuedAttribute> im;

        /**
         * Gets the value of the im property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the im property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIm().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getIm() {
            if (im == null) {
                im = new ArrayList<MultiValuedAttribute>();
            }
            return this.im;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="phoneNumber" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class PhoneNumbers {

        private List<MultiValuedAttribute> phoneNumber;

        /**
         * Gets the value of the phoneNumber property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the phoneNumber property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPhoneNumber().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getPhoneNumber() {
            if (phoneNumber == null) {
                phoneNumber = new ArrayList<MultiValuedAttribute>();
            }
            return this.phoneNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="photo" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    public static class Photos {

        private List<MultiValuedAttribute> photo;

        /**
         * Gets the value of the photo property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the photo property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPhoto().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getPhoto() {
            if (photo == null) {
                photo = new ArrayList<MultiValuedAttribute>();
            }
            return this.photo;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="role" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */

    public static class Roles {

        private List<MultiValuedAttribute> role;

        /**
         * Gets the value of the role property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the role property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRole().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getRole() {
            if (role == null) {
                role = new ArrayList<MultiValuedAttribute>();
            }
            return this.role;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="x509Certificate" type="{urn:scim:schemas:core:1.0}multiValuedAttribute" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */

    public static class X509Certificates {

        private List<MultiValuedAttribute> x509Certificate;

        /**
         * Gets the value of the x509Certificate property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the x509Certificate property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getX509Certificate().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link MultiValuedAttribute }
         */
        public List<MultiValuedAttribute> getX509Certificate() {
            if (x509Certificate == null) {
                x509Certificate = new ArrayList<>();
            }
            return this.x509Certificate;
        }

    }

}
